package workflow

import (
	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/testsuite"

	"github.com/2SSK/tenantflow/internal/activities"
	"github.com/2SSK/tenantflow/internal/billing"
	"github.com/2SSK/tenantflow/internal/model"
)

// matrixTenant is the tenant every matrix case runs against. Workflow IDs are
// generated by the testsuite, but tenant arguments are explicit, so all mock
// matching keys off this constant.
const matrixTenant = "matrix-t1"

// compRule describes one saga compensation activity: it MUST run when the
// failed activity's index in the workflow's ordered activity list falls
// inside [minIndex, maxIndex], and MUST NOT run otherwise. The ranges encode
// the guard-flag progress each workflow tracks (e.g. provision only drops the
// database once ProvisionTenant succeeded).
type compRule struct {
	activity string
	minIndex int
	maxIndex int
	args     []any // call args appended after the ctx mock
}

func rule(activity string, minIdx, maxIdx int, args ...any) compRule {
	return compRule{activity: activity, minIndex: minIdx, maxIndex: maxIdx, args: args}
}

// workflowMatrix maps one saga to its ordered activities, its compensation
// rules, and its terminal failure audit activity.
type workflowMatrix struct {
	name        string
	wf          any
	input       any
	activities  []string
	comps       []compRule
	terminal    string // terminal failure activity; always runs via the defer
	successArgs []any  // args (after ctx) the success terminal is invoked with
	register    func(env *testsuite.TestWorkflowEnvironment)
	mock        func(env *testsuite.TestWorkflowEnvironment, failName string)
}

// mockActivity registers the mock for one activity call. When failName equals
// the activity, the mock returns (zeros..., err) so the test forces exactly
// that activity to fail; otherwise it returns the success values. ok must be
// the full success return tuple; failZeros are the zero values for every
// return EXCEPT the final error, which the helper appends.
func mockActivity(env *testsuite.TestWorkflowEnvironment, failName, name string, ok []any, failZeros []any, args ...any) {
	c := env.OnActivity(name, append([]any{mock.Anything}, args...)...)
	if failName == name {
		ret := append([]any{}, failZeros...)
		ret = append(ret, fmt.Errorf("matrix failure of %s", name))
		c.Return(ret...)
		return
	}
	c.Return(ok...)
}

// matrices enumerates all six sagas with their ordered activities and
// compensation rules. The activity indices in compRule refer to the position
// in that workflow's activities slice.
var matrices = []workflowMatrix{
	{
		name:  "provision",
		wf:    ProvisionTenantWorkflow,
		input: ProvisionInput{TenantID: matrixTenant, IsolationMode: "dedicated"},
		activities: []string{
			activities.CreateTenantRecordActivityName,      // 0
			activities.ProvisionTenantActivityName,         // 1 — sets dbCreated
			activities.ProvisionTenantIdentityActivityName, // 2 — sets userID
			activities.MarkTenantActiveActivityName,        // 3 — success terminal
		},
		comps: []compRule{
			rule(activities.DropTenantDatabaseActivityName, 2, 3, matrixTenant),
			rule(activities.DeleteTenantIdentityActivityName, 3, 3, "kc-user-1"),
		},
		terminal:    activities.MarkTenantFailedActivityName,
		successArgs: []any{matrixTenant},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewProvisionActivities(nil, nil, nil))
			env.RegisterActivity(activities.NewIdentityActivities(nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.CreateTenantRecordActivityName, []any{nil}, nil, matrixTenant, mock.Anything, "dedicated")
			mockActivity(env, failName, activities.ProvisionTenantActivityName, []any{nil}, nil, matrixTenant, "dedicated")
			mockActivity(env, failName, activities.ProvisionTenantIdentityActivityName, []any{"kc-user-1", nil}, []any{""}, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantActiveActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.DropTenantDatabaseActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.DeleteTenantIdentityActivityName, []any{nil}, nil, "kc-user-1")
			mockActivity(env, failName, activities.MarkTenantFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
	{
		name:  "upgrade",
		wf:    UpgradeTenantWorkflow,
		input: UpgradeInput{TenantID: matrixTenant},
		activities: []string{
			activities.MarkTenantUpgradingActivityName, // 0
			activities.VerifyTenantActiveActivityName,  // 1 — returns old quota
			activities.RaiseQuotasActivityName,         // 2 — sets quotaRaised
			activities.EnableFeaturesActivityName,      // 3
			activities.UpdateBillingActivityName,       // 4
			activities.MarkTenantUpgradedActivityName,  // 5 — success terminal
		},
		comps: []compRule{
			rule(activities.RollbackQuotasActivityName, 3, 5, matrixTenant, oldQuota),
		},
		terminal:    activities.MarkTenantUpgradeFailedActivityName,
		successArgs: []any{matrixTenant},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewUpgradeActivities(nil, nil, nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.MarkTenantUpgradingActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.VerifyTenantActiveActivityName, []any{oldQuota, nil}, []any{billing.Quota{}}, matrixTenant)
			mockActivity(env, failName, activities.RaiseQuotasActivityName, []any{newQuota, nil}, []any{billing.Quota{}}, matrixTenant, oldQuota)
			mockActivity(env, failName, activities.EnableFeaturesActivityName, []any{nil}, nil, matrixTenant, mock.Anything)
			mockActivity(env, failName, activities.UpdateBillingActivityName, []any{nil}, nil, matrixTenant, mock.Anything)
			mockActivity(env, failName, activities.RollbackQuotasActivityName, []any{nil}, nil, matrixTenant, oldQuota)
			mockActivity(env, failName, activities.MarkTenantUpgradedActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantUpgradeFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
	{
		name:  "migrate",
		wf:    MigrateTenantWorkflow,
		input: MigrateInput{TenantID: matrixTenant},
		activities: []string{
			activities.MarkTenantMigratingActivityName, // 0
			activities.MigrateDataActivityName,         // 1 — returns backup name
			activities.SwitchTrafficActivityName,       // 2 — sets switched
			activities.MarkTenantMigratedActivityName,  // 3 — success terminal
		},
		comps: []compRule{
			// Before the switch the live DB is untouched; drop the disposable
			// _new DB. After the switch there is no aux DB left to drop.
			rule(activities.DropTenantAuxDatabaseActivityName, 0, 2, matrixTenant),
		},
		terminal:    activities.MarkTenantMigrateFailedActivityName,
		successArgs: []any{matrixTenant},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewMigrateActivities(nil, nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.MarkTenantMigratingActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MigrateDataActivityName, []any{auxBackupName, nil}, []any{""}, matrixTenant)
			mockActivity(env, failName, activities.SwitchTrafficActivityName, []any{nil}, nil, matrixTenant, auxBackupName)
			mockActivity(env, failName, activities.DropTenantAuxDatabaseActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantMigratedActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantMigrateFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
	{
		name:  "backup",
		wf:    BackupTenantWorkflow,
		input: BackupInput{TenantID: matrixTenant},
		activities: []string{
			activities.MarkTenantBackingUpActivityName, // 0
			activities.BackupTenantDataActivityName,    // 1 — returns backup record
			activities.MarkTenantBackedUpActivityName,  // 2 — success terminal
		},
		comps:       nil, // backup never mutates the live DB; nothing to roll back
		terminal:    activities.MarkTenantBackupFailedActivityName,
		successArgs: []any{matrixTenant, int64(123), backupName},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewBackupActivities(nil, nil, nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.MarkTenantBackingUpActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.BackupTenantDataActivityName, []any{backupRecord, nil}, []any{nil}, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantBackedUpActivityName, []any{nil}, nil, matrixTenant, int64(123), backupName)
			mockActivity(env, failName, activities.MarkTenantBackupFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
	{
		name:  "restore",
		wf:    RestoreTenantWorkflow,
		input: RestoreInput{TenantID: matrixTenant, BackupID: 456},
		activities: []string{
			activities.MarkTenantRestoringActivityName, // 0
			activities.PreRestoreSnapshotActivityName,  // 1 — sets preSnapshotTaken
			activities.RestoreDataActivityName,         // 2
			activities.MarkTenantRestoredActivityName,  // 3 — success terminal
		},
		comps: []compRule{
			// Once the pre-restore snapshot exists, any later failure must roll
			// the live DB back to it.
			rule(activities.RestoreRollbackActivityName, 2, 3, matrixTenant, preBackupName),
		},
		terminal:    activities.MarkTenantRestoreFailedActivityName,
		successArgs: []any{matrixTenant, int64(456)},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewRestoreActivities(nil, nil, nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.MarkTenantRestoringActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.PreRestoreSnapshotActivityName, []any{preBackupName, nil}, []any{""}, matrixTenant)
			mockActivity(env, failName, activities.RestoreDataActivityName, []any{nil}, nil, matrixTenant, int64(456))
			mockActivity(env, failName, activities.MarkTenantRestoredActivityName, []any{nil}, nil, matrixTenant, int64(456))
			mockActivity(env, failName, activities.RestoreRollbackActivityName, []any{nil}, nil, matrixTenant, preBackupName)
			mockActivity(env, failName, activities.MarkTenantRestoreFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
	{
		name:  "delete",
		wf:    DeleteTenantWorkflow,
		input: DeleteInput{TenantID: matrixTenant, GracePeriod: 30 * 24 * time.Hour},
		activities: []string{
			activities.MarkTenantDeletingActivityName, // 0
			activities.BackupTenantDataActivityName,   // 1 — version-gated pre-delete backup
			activities.DeprovisionTenantActivityName,  // 2
			activities.MarkTenantDeletedActivityName,  // 3 — success terminal
		},
		// Teardown deliberately has no compensation: reviving a half-torn-down
		// tenant would be a lie, so failure only audits TENANT_DELETE_FAILED.
		comps:       nil,
		terminal:    activities.MarkTenantDeleteFailedActivityName,
		successArgs: []any{matrixTenant},
		register: func(env *testsuite.TestWorkflowEnvironment) {
			env.RegisterActivity(activities.NewDeprovisionActivities(nil, nil))
			env.RegisterActivity(activities.NewCancelDeleteActivities(nil, nil))
			env.RegisterActivity(activities.NewBackupActivities(nil, nil, nil))
		},
		mock: func(env *testsuite.TestWorkflowEnvironment, failName string) {
			mockActivity(env, failName, activities.MarkTenantDeletingActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.BackupTenantDataActivityName, []any{backupRecord, nil}, []any{nil}, matrixTenant)
			mockActivity(env, failName, activities.DeprovisionTenantActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantDeletedActivityName, []any{nil}, nil, matrixTenant)
			mockActivity(env, failName, activities.MarkTenantDeleteFailedActivityName, []any{nil}, nil, matrixTenant)
		},
	},
}

// Shared fixtures for mocked activity return values.
var (
	oldQuota      = billing.Quota{MaxUsers: 100, MaxStorageGB: 50, MaxSeats: 3}
	newQuota      = billing.Quota{MaxUsers: 500, MaxStorageGB: 250, MaxSeats: 15}
	auxBackupName = "backup-matrix-1"
	preBackupName = "pre-matrix-1"
	backupName    = "matrix-1.tar.gz"
	backupRecord  = &model.Backup{ID: 123, Filename: backupName}
)

// TestFailEveryActivity is the fail-every-activity matrix: for EVERY activity
// of EVERY workflow, force exactly that activity to fail and verify the saga:
//
//   - the workflow ends with an error;
//   - the terminal failure audit activity always runs (its deferred
//     compensation path);
//   - each compensation rule runs exactly when the failure position calls for
//     it (index inside [min, max]) and never otherwise;
//   - the success terminal never runs when a step before it failed.
//
// The recorder's DLQ mirror is covered separately in internal/instance
// (recorder_test.go); here we prove the sagas' compensation behavior, which is
// what the audit trail reflects.
func TestFailEveryActivity(t *testing.T) {
	for _, m := range matrices {
		for i, actName := range m.activities {
			t.Run(m.name+"/"+actName, func(t *testing.T) {
				env := (&testsuite.WorkflowTestSuite{}).NewTestWorkflowEnvironment()
				m.register(env)
				m.mock(env, actName)

				env.ExecuteWorkflow(m.wf, m.input)

				if !env.IsWorkflowCompleted() {
					t.Fatal("workflow did not complete")
				}
				if env.GetWorkflowError() == nil {
					t.Fatalf("expected workflow error when %s fails, got nil", actName)
				}

				// The deferred failure path must always audit.
				env.AssertCalled(t, m.terminal, mock.Anything, matrixTenant)

				// Compensation must run exactly where the guard flags demand.
				for _, c := range m.comps {
					args := append([]any{mock.Anything}, c.args...)
					if i >= c.minIndex && i <= c.maxIndex {
						env.AssertCalled(t, c.activity, args...)
					} else {
						env.AssertNotCalled(t, c.activity, args...)
					}
				}

				// The success terminal must not run unless it was the failed
				// activity itself. Assert with the exact args the workflow
				// passes on the happy path.
				last := m.activities[len(m.activities)-1]
				lastArgs := append([]any{mock.Anything}, m.successArgs...)
				if i < len(m.activities)-1 {
					env.AssertNotCalled(t, last, lastArgs...)
				} else {
					env.AssertCalled(t, last, lastArgs...)
				}
			})
		}
	}
}
